### ISSUE TITLE
Тебе не надо

### ISSUE THREAD

**Issue by Graviton31** [waxmater/WebTaskManager#5]
Тебе не надо

_Originally posted by @Graviton31 in https://github.com/waxmater/WebTaskManager/issues/4#issuecomment-2473235542_

**Comment by Graviton31** [comment]
> ```
>           Тебе не надо
> ```
> 
> _Originally posted by @Graviton31 in [#4 (comment)](https://github.com/waxmater/WebTaskManager/pull/4#issuecomment-2473235542)_

**Comment by waxmater** [comment]
ЛОЖ!
